name: unit test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  unit_tests_nightly_pytorch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install  --no-build-isolation -e .
          conda install pytorch cpuonly -c pytorch-nightly
      - name: Run unit tests with coverage
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pytest --cov=. --cov-report xml tests -vv
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
  unit_tests_stable_pytorch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install  --no-build-isolation -e .
      - name: Run unit tests with coverage
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pytest --cov=. --cov-report xml tests -vv
